# 1. 基础镜像: riscv64/ubuntu:22.04
ARG ARM_ARCH=riscv64
FROM ${ARM_ARCH}/ubuntu:22.04

# 2. 设置环境变量和 Locale
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    ROS_DISTRO=humble

# 3. 安装构建工具和基础依赖 (APT)
# 针对 ros_base，我们移除了庞大的 Qt5/X11 开发库，保留核心构建工具
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    curl \
    wget \
    # Python 基础
    python3-pip \
    python3-yaml \
    python3-dev \
    python3-numpy \
    python3-lxml \
    python3-netifaces \
    # 核心 C++ 依赖
    libeigen3-dev \
    libacl1-dev \
    libssl-dev \
    libxml2-dev \
    libxslt-dev \
    libyaml-cpp-dev \
    libffi-dev \
    # LTTng (ROS 2 核心性能分析工具，Humble 必须)
    liblttng-ust-dev \
    liblttng-ctl-dev \
    # 其他常用依赖
    libtinyxml2-dev \
    libasio-dev \
    libbullet-dev \
    libcurl4-openssl-dev \
    libspdlog-dev \
    ninja-build \
    && rm -rf /var/lib/apt/lists/*

# 4. 安装 Python 工具 (PIP)
# 锁定 Humble 版本的关键工具
ENV PIP_BREAK_SYSTEM_PACKAGES=1
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -U \
    colcon-common-extensions \
    vcstool \
    rosdepc \
    empy==3.3.4 \
    lark \
    pytest \
    catkin_pkg \
    pyparsing \
    pyyaml

# 5. 初始化 rosdepc
RUN rosdepc init
RUN rosdepc update

# 6. 创建工作区并下载源码
RUN mkdir -p /ros2_ws/src
WORKDIR /ros2_ws

# 1. 下载你的仓库 (Humble 分支)
# 2. 额外克隆 ros2/variants，因为它定义了什么是 "ros_base"
RUN wget https://raw.githubusercontent.com/jialog0301/ros2/humble/ros2.repos \
    && vcs import src < ros2.repos \
    && git clone -b humble https://github.com/ros2/variants src/ros2/variants

# 7. 安装源码依赖 (Rosdep)
# 跳过 GUI 和不需要的中间件
RUN rosdepc install -i --from-path src --rosdistro humble -y \
    --skip-keys "fastrtps rti-connext-dds-6.0.1 mimick qt_gui_cpp sip python3-sip"


RUN colcon build --event-handlers console_cohesion+ \
    --merge-install \
    --install-base /opt/ros/humble \
    --packages-up-to ros_base \
    --cmake-args -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
WORKDIR /
CMD ["bash"]